export const pricingTiers = [
  {
    id: 'essential',
    name: 'Essential Clean',
    price: '€75',
    period: 'per session',
    description: 'Perfect for regular upkeep of small to medium homes.',
    features: [
      'General tidying and dusting',
      'Vacuuming and mopping all floors',
      'Bathroom cleaning and sanitisation',
      'Kitchen surface and sink cleaning',
      'Bin emptying and rubbish removal',
      'Up to 3 hours of cleaning',
    ],
    highlighted: false,
    cta: 'Get Started',
  },
  {
    id: 'deep',
    name: 'Deep Clean',
    price: '€150',
    period: 'per session',
    description: 'Intensive top-to-bottom cleaning for a thorough refresh.',
    features: [
      'Everything in Essential Clean',
      'Inside oven and appliance cleaning',
      'Skirting board and baseboard cleaning',
      'Window sills and interior glass',
      'Tile and grout scrubbing',
      'Up to 6 hours of cleaning',
    ],
    highlighted: true,
    cta: 'Most Popular',
  },
  {
    id: 'premium',
    name: 'Premium Clean',
    price: '€250',
    period: 'per session',
    description: 'Our most comprehensive service for a complete property transformation.',
    features: [
      'Everything in Deep Clean',
      'Carpet and upholstery treatment',
      'Full window cleaning (interior & exterior)',
      'Wall washing and scuff removal',
      'Garage or utility room cleaning',
      'Up to 10 hours of cleaning',
    ],
    highlighted: false,
    cta: 'Go Premium',
  },
];
